stages:
  - build-job
  - test

build-job:
  stage: build-job
  script:
    - docker build -t journalplus-image .

test-job:
  stage: test
  script:
    - docker run --rm journalplus-image ./gradlew test