
stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - apk update && apk add findutils
  - find --version
  - chmod +x ./gradlew

build-job:
  stage: build
  tags:
    - linux
  script:
    - "./gradlew clean build -x test"
  artifacts:
    paths:
      - build/libs/*jar
    expire_in: 1 week

test:
  stage: test
  tags:
    - linux
  script:
    - ./gradlew test
  artifacts:
    reports:
      junit: build/test-results/test/
