stages:
  - build
  - test

before_script:
  - cp ${ENV_FILE} .env.ci

build-job:
  stage: build
  script:
    - docker build -t journalplus-image .

test-job:
  stage: test
  script:
    - cp .env.ci .env
    - docker run --rm -v $(pwd)/.env:/app/.env journalplus-image ./gradlew test
