stages:
  - build
  - test

build-job:
  stage: build
  script:
    - docker build -t journalplus-image .

test-job:
  stage: test
  script:
    - mkdir -p /tmp/secure_files
    - cp /builds/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/.env /tmp/secure_files/.env
    - docker run --rm -v /tmp/secure_files/.env:/app/.env journalplus-image ./gradlew test