stages:
  - build
  - test

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - cp "$ENV_FILE" .env

build:
  stage: build
  image: gradle:8.11.0-jdk17-alpine
  script:
    - gradle clean build -x test
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

test:
  stage: test
  image: gradle:8.11.0-jdk17-alpine
  script:
    - gradle test
  artifacts:
    when: always
    paths:
      - build/test-results
      - build/reports/tests/test/index.html
    expire_in: 1 week