stages:
  - build
  - test

before_script:
  - echo "Checking if .env file exists..."
  - ls -l .env  # Проверяем, существует ли .env
  - cp ${ENV_FILE} .env  # Копируем .env из файла

build-job:
  stage: build
  script:
    - docker build -t journalplus-image .

test-job:
  stage: test
  script:
    - docker run --rm -v $(pwd)/.env:/app/.env journalplus-image ./gradlew test