stages:
  - build
  - test

before_script:
  - test -f "${ENV_FILE}" && echo "Файл существует" || echo "Файл не существует"
  - cp "$ENV_FILE" .env
  - cat .env

build-job:
  stage: build
  script:
    - cat .env
    - docker build -t journalplus-image .

test-job:
  stage: test
  script:
    - docker-compose up postgres -d
    - docker run --rm --env-file .env journalplus-image ./gradlew test
    - docker-compose down
