stages:
  - build
  - test
  
build-job:
  stage: build
  script:
    - docker build -t journalplus-image .

test-job:
  stage: test
  script:
    - docker run --rm journalplus-image ./gradlew test

