image: openjdk:17-jdk-slim

stages:
  - build
  - setup
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - apt-get update && apt-get install -y findutils
  - find --version
  - chmod +x ./gradlew

setup_postgres:
  stage: setup
  image: docker:20.10.16
  tags:
    - linux
  services:
    - name: postgres:latest
      alias: db
  variables:
    POSTGRES_USER: root
    POSTGRES_PASSWORD: rootroot
  script:
    - docker run --name postgres -e POSTGRES_USER=$POSTGRES_USER -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -d -p 5432:5432 postgres:latest
    - until pg_isready -h db -p 5432; do sleep 1; done
    - psql -h db -U $POSTGRES_USER -c "CREATE DATABASE journal_plus_db;"

build-job:
  stage: build
  tags:
    - linux
  script:
    - "./gradlew clean build -x test"
  artifacts:
    paths:
      - build/libs/*jar
    expire_in: 1 week
  only:
    - main

test:
  stage: test
  tags:
    - linux
  script:
    - export $(cat .env)
    - ./gradlew test
