stages:
  - build-job
  - test

build-job:
  stage: build-job
  script:
    - docker build -t journal-plus:latest .
    - docker run

test-job:
  stage: test
  services:
    - name: postgres:latest
      alias: db
      command: ["postgres", "-c", "fsync=off"]
  script:
    - echo "Running tests..."
    - docker run --rm --network host -e DB_HOST=db -e DB_PORT=5432 -e DB_USER=$DB_USER -e DB_PASSWORD=$DB_PASSWORD -e DB_NAME=$DB_NAME journal-plus:latest ./gradlew test
    - echo "Tests completed."

after_script:
  - docker system prune -af