stages:
  - build
  - test

variables:
  SECURE_FILES_DOWNLOAD_PATH: './where/files/should/go/' 

build-job:
  stage: build
  script:
    - docker build -t journalplus-image .

test-job:
  stage: test
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - mv $SECURE_FILES_DOWNLOAD_PATH/.env /tmp/secure_files/.env
    - docker run --rm -v /tmp/secure_files/.env:/app/.env journalplus-image ./gradlew test
  dependencies:
    - build-job