stages:
  - build
  - test

build-job:
  stage: build
  script:
    - docker build -t journalplus-image .

test-job:
  stage: test
  script:
    - echo "Running tests in Docker container..."
    - docker run --rm --env-file $ENV_FILE journalplus-image ./gradlew test