services:
  postgresql:
    image: postgres:latest
    container_name: database_postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: journalplus-image:latest
    container_name: journalplus-container
    env_file:
      - .env
    ports:
      - 8080:8080
    command: "./gradlew bootRun"

volumes:
  postgres_data:
